
import React, { createContext, useState, useContext, ReactNode } from "react";

// Define available languages
export type Language = "en" | "ua";

// Define the context type
type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

// Create context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

// Translation data for both languages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.schedule": "Schedule",
    "nav.team": "Team",
    "nav.aboutTheater": "About the Theater",
    "nav.news": "News",
    "nav.theaterHistory": "Theater History",
    "nav.visitRules": "Visit Rules",
    "nav.contacts": "Contacts",
    "nav.profile": "Profile",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.logout": "Logout",
    "nav.admin": "Admin",
    
    // Schedule page
    "schedule.title": "Performance Schedule",
    "schedule.subtitle": "Browse and book our upcoming performances",
    "schedule.allMonths": "All Months",
    "schedule.moreDetails": "More Details",
    "schedule.buyTickets": "Buy Tickets",
    "schedule.ticketsFrom": "Tickets from",
    "schedule.director": "Director",
    "schedule.noPerformances": "No performances found",
    "schedule.noPerformancesSubtitle": "There are no performances scheduled for this period.",

    // About pages
    "about.history": "Theater History",
    "about.rules": "Visit Rules",
    "about.disabled": "For Persons with Disabilities",
    "about.privileged": "Visiting the Theater by Privileged Categories of Citizens",
    "about.contacts": "Contacts",
    "about.redirecting": "Redirecting to Theater History page...",
    
    // Search
    "search.title": "Search",
    "search.placeholder": "Search for performances, actors, news...",
    "search.button": "Search",
    "search.results": "Found {count} result",
    "search.results_plural": "Found {count} results",
    "search.noResults": "No results found",
    "search.tryAgain": "Try different keywords or check the spelling",
    
    // Admin Panel
    "admin.title": "Admin",
    "admin.performances": "Performances Management",
    "admin.performances.subtitle": "Manage theater performances - add, edit, and delete shows.",
    "admin.tickets": "Ticket Pricing",
    "admin.tickets.subtitle": "Set and update ticket prices for different sections.",
    "admin.reports": "Transaction Reports",
    "admin.reports.subtitle": "Generate and export transaction reports.",
    "admin.salaries": "Employee Salaries",
    "admin.salaries.subtitle": "Calculate salaries for theater employees.",
    "admin.news": "News Management",
    "admin.news.subtitle": "Manage news articles - create, edit, and delete news.",
    
    "admin.add": "Add New",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.confirm": "Confirm",
    
    "admin.performances.title": "Performances",
    "admin.performances.new": "New Performance",
    "admin.performances.edit": "Edit Performance",
    "admin.performances.name": "Performance Name",
    "admin.performances.date": "Date",
    "admin.performances.time": "Time",
    "admin.performances.actions": "Actions",
    "admin.performances.addNewButton": "Add New",
    "admin.performances.ActorButton": "Add Actor",
    "admin.performances.addCreativeButton": "Add Creative",
    "admin.performances.nameHuman": "Name",
    "admin.performances.roleHuman": "Role",
    "admin.performances.description": "Description",
    "admin.performances.photos": "Photos",
    "admin.performances.participants": "Participants",
    "admin.performances.director": "Director",
    "admin.performances.actors": "Actors",
    "admin.performances.creativeTeam": "Creative Team",
    "admin.performances.uploadPhoto": "Upload Photo",
    
    "admin.tickets.title": "Ticket Pricing",
    "admin.tickets.performance": "Performance",
    "admin.tickets.section": "Section",
    "admin.tickets.price": "Price",
    "admin.tickets.setPrice": "Set Price",
    "admin.tickets.currency": "UAH",
    "admin.tickets.actions": "Actions",
    
    "admin.reports.title": "Transaction Reports",
    "admin.reports.dateRange": "Date Range",
    "admin.reports.from": "From",
    "admin.reports.to": "To",
    "admin.reports.generate": "Generate Report",
    "admin.reports.export": "Export to Excel",
    "admin.reports.total": "Total Revenue",
    "admin.reports.ticketsSold": "Tickets Sold",
    "admin.reports.sum": "Summary",
    "admin.reports.performance": "Performance",
    "admin.reports.section": "Section",
    "admin.reports.date": "Date",
    "admin.reports.price": "Price", 
    "admin.reports.customer": "Customer",
    
    "admin.salaries.title": "Employee Salaries",
    "admin.salaries.calculateTitle": "Calculate Salary",
    "admin.salaries.employee": "Employee",
    "admin.salaries.hours": "Working Hours",
    "admin.salaries.rate": "Hourly Rate",
    "admin.salaries.total": "Total Salary",
    "admin.salaries.calculate": "Calculate Salary",
    "admin.salaries.setRate": "Set Rate",
    "admin.salaries.currentHourlyRate": "Current hourly rate:",
    "admin.salaries.selectEmployee": "Select an employee",
    "admin.salaries.setHourlyRate": "Set Hourly Rate",
    "admin.salaries.setHourlyRateEmployee": "Setting hourly rate for",
    "admin.salaries.currentRate": "Current Rate",
    "admin.salaries.newRate": "New Rate",
    "admin.salaries.name": "Name",
    "admin.salaries.position": "Position",
    "admin.salaries.actions": "Actions",
    "admin.salaries.cancelButton": "Cancel",
    "admin.salaries.saveButton": "Save",
    "admin.salaries.addEmployee": "Add Employee",
    "admin.salaries.workingDays": "Working Days",
    "admin.salaries.dailySalary": "Daily Salary",
    "admin.salaries.monthlySalary": "Monthly Salary",
    "admin.salaries.editSuccess": "Information edited",
    "admin.salaries.editSuccessDesc": "Information about the employee has been successfully edited.",
    "admin.salaries.addSuccess": "Employee Added",
    "admin.salaries.addSuccessDesc": "New employee has been successfully added.",
    "admin.salaries.deleteSuccess": "Employee deleted",
    "admin.salaries.deleteSuccessDesc": "The employee has been successfully removed.",
    "admin.salaries.editEmployee": "Edit Employee",

    "admin.news.title": "News Management",
    "admin.news.new": "New Article",
    "admin.news.edit": "Edit Article",
    "admin.news.articleTitle": "Title",
    "admin.news.content": "Content",
    "admin.news.date": "Publication Date",
    "admin.news.photo": "Photo",
    "admin.news.uploadPhoto": "Upload Photo",
    "admin.news.add": "Add Article",
    "admin.news.save": "Save Article",

    // Home page
    "home.hero.title": "Experience the Magic of Live Theatre",
    "home.hero.subtitle": "Book your tickets now for the most captivating performances at TheatreTix",
    "home.button.schedule": "View Schedule",
    "home.button.signin": "Sign In",
    
    "home.upcoming.title": "Upcoming Performances",
    "home.upcoming.subtitle": "Don't miss these spectacular shows",
    "home.upcoming.button": "View All Shows",
    
    "home.whyus.title": "Why Choose TheatreTix?",
    "home.whyus.feature1.title": "Curated Performances",
    "home.whyus.feature1.text": "We carefully select the most captivating and entertaining shows for your enjoyment.",
    "home.whyus.feature2.title": "Easy Booking",
    "home.whyus.feature2.text": "Our intuitive platform makes it simple to find and book the perfect seats for any show.",
    "home.whyus.feature3.title": "Exclusive Discounts",
    "home.whyus.feature3.text": "Special offers and discounts for members and frequent theatergoers.",
    "home.whyus.button": "Join TheatreTix",
    
    "home.testimonials.title": "What Our Audience Says",
    "home.testimonials.review1.text": "The performance of Hamlet was breathtaking. I was on the edge of my seat the entire time.",
    "home.testimonials.review1.name": "James Wilson",
    "home.testimonials.review1.role": "Theater Enthusiast",
    "home.testimonials.review2.text": "Booking tickets was so easy, and the seats were exactly as described. Will definitely use TheatreTix again!",
    "home.testimonials.review2.name": "Sarah Johnson",
    "home.testimonials.review2.role": "Regular Visitor",
    "home.testimonials.review3.text": "The costumes and set design for Romeo and Juliet were absolutely stunning. A visual feast!",
    "home.testimonials.review3.name": "Michael Brown",
    "home.testimonials.review3.role": "Art Director",
    
    "home.newsletter.title": "Stay Updated",
    "home.newsletter.text": "Subscribe to our newsletter and be the first to know about upcoming shows, special promotions, and exclusive events.",
    "home.newsletter.placeholder": "Enter your email",
    "home.newsletter.button": "Subscribe",

    // Footer
    "footer.description": "TheatreTix is your premier destination for theater performances in the city. We provide an unforgettable cultural experience with a diverse range of classical and contemporary productions.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.hours": "Hours",
    "footer.address": "50 Volodymyrska St.",
    "footer.phone": "+380 44 123 4567",
    "footer.email": "info@theatretix.com",
    "footer.weekdays": "Mon-Fri: 9:00 AM - 8:00 PM",
    "footer.weekends": "Sat-Sun: 10:00 AM - 6:00 PM",
    "footer.allRights": "All rights reserved",
    "footer.privacy": "Privacy Policy",
    "footer.termsService": "Terms of Service",
    "footer.refund": "Refund Policy",

    // Team
    "team.title": "Our Team",
    "team.tabs.management": "Management",
    "team.tabs.actors": "Actors",
    "team.tabs.creative": "Creative Team",
    "team.tabs.directors": "Directors",
    
    "team.management.title": "Theater Management",
    "team.management.person1.name": "Alexandra Davis",
    "team.management.person1.role": "Artistic Director",
    "team.management.person1.bio": "Alexandra has been with TheatreTix for over 15 years, previously working with the Royal Shakespeare Company.",
    "team.management.person2.name": "Michael Chen",
    "team.management.person2.role": "Executive Director",
    "team.management.person2.bio": "With a background in both theater and business administration, Michael oversees all operational aspects of TheatreTix.",
    "team.management.person3.name": "Olivia Johnson",
    "team.management.person3.role": "Production Manager",
    "team.management.person3.bio": "Olivia coordinates all production elements across our performance schedule to ensure seamless operations.",
    
    "team.actors.title": "Our Actors",
    "team.actors.person1.name": "James Miller",
    "team.actors.person1.role": "Classical Theater",
    "team.actors.person1.bio": "James specializes in Shakespeare and classical theater roles, bringing decades of experience to our stage.",
    "team.actors.person2.name": "Sofia Rodriguez",
    "team.actors.person2.role": "Musical Theater",
    "team.actors.person2.bio": "With her powerful voice and expressive acting, Sofia has become a favorite in our musical productions.",
    "team.actors.person3.name": "Daniel Kim",
    "team.actors.person3.role": "Contemporary Drama",
    "team.actors.person3.bio": "Daniel's emotional range and versatility make him perfect for our modern dramatic productions.",
    "team.actors.person4.name": "Nadia Patel",
    "team.actors.person4.role": "Comedy",
    "team.actors.person4.bio": "Nadia's impeccable timing and physical comedy skills have audiences laughing night after night.",
    "team.actors.person5.name": "Thomas Wilson",
    "team.actors.person5.role": "Character Actor",
    "team.actors.person5.bio": "Known for his ability to transform into any role, Thomas is one of our most versatile performers.",
    "team.actors.person6.name": "Aisha Johnson",
    "team.actors.person6.role": "Drama & Dance",
    "team.actors.person6.bio": "Combining exceptional acting with professional dance training, Aisha brings unique energy to our productions.",
    
    "team.creative.title": "Creative Team",
    "team.creative.person1.name": "Eliza Thompson",
    "team.creative.person1.role": "Head Costume Designer",
    "team.creative.person1.bio": "With training from the Fashion Institute, Eliza creates our stunning period and contemporary costumes.",
    "team.creative.person2.name": "Robert Santos",
    "team.creative.person2.role": "Set Designer",
    "team.creative.person2.bio": "Robert's innovative and practical set designs transform our stage for each unique production.",
    "team.creative.person3.name": "Mei Lin",
    "team.creative.person3.role": "Lighting Designer",
    "team.creative.person3.bio": "Award-winning lighting designer who creates atmospheric and emotional environments through light.",
    "team.creative.person4.name": "Carlos Mendez",
    "team.creative.person4.role": "Sound Designer",
    "team.creative.person4.bio": "Carlos crafts immersive soundscapes that enhance the theatrical experience of every production.",
    "team.creative.person5.name": "Hannah Wright",
    "team.creative.person5.role": "Prop Master",
    "team.creative.person5.bio": "Hannah sources and creates the perfect props that help bring our stories to life.",
    
    "team.directors.title": "Our Directors",
    "team.directors.person1.name": "Victoria Bennett",
    "team.directors.person1.role": "Classical Productions",
    "team.directors.person1.bio": "Victoria's interpretations of classical works balance tradition with fresh perspectives for modern audiences.",
    "team.directors.person2.name": "Jonathan Parker",
    "team.directors.person2.role": "New Works & Contemporary Plays",
    "team.directors.person2.bio": "Jonathan collaborates with playwrights to bring new voices and stories to our theater.",
    "team.directors.person3.name": "Sandra Miller",
    "team.directors.person3.role": "Musical Direction",
    "team.directors.person3.bio": "With a background in music and theater, Sandra directs our most ambitious musical productions.",

    // About Theater History
    "history.title": "Theater History",
    "history.intro": "Our theater has a rich history dating back over a century, evolving from humble beginnings to become one of the country's premier cultural institutions.",
    "history.section1.title": "The Early Years (1920-1945)",
    "history.section1.text": "Founded in 1920 by renowned director and playwright Anton Mikhailov, our theater began as a small experimental stage in the heart of the city. During its first decades, the theater established itself as a hub for innovative performances and launched the careers of many celebrated actors.",
    "history.section1.caption": "Original theater building, circa 1925",
    "history.section2.title": "Golden Age (1945-1970)",
    "history.section2.text": "The post-war period marked the theater's golden age, with legendary productions of classical and contemporary works that gained international recognition. Under the leadership of Maria Stepanova, the theater expanded its repertoire and attracted the finest talents in the country.",
    "history.section2.caption": "Renowned production of 'The Cherry Orchard', 1956",
    "history.section3.title": "Modern Era (1970-Present)",
    "history.section3.text": "The last decades have seen our theater embrace cutting-edge productions while honoring theatrical traditions. Major renovations in 2010 modernized our facilities while preserving the historic charm of our main building. Today, we continue to push boundaries and engage with audiences through powerful storytelling and artistic excellence.",
    "history.section3.caption": "The renovated main stage, 2012",
    "history.section4.title": "Awards and Recognition",
    "history.section4.text": "Throughout its history, TheatreTix has received numerous awards and accolades, including:",
    "history.section4.point1": "National Theater Excellence Award (1978, 1992, 2008)",
    "history.section4.point2": "Regional Theater of the Year (2012, 2019)",
    "history.section4.point3": "Community Arts Impact Award (annually since 2005)",
    "history.section4.point4": "Historic Preservation Award for our building restoration (2015)",
    "history.section5.title": "Our Centennial Celebration",
    "history.section5.text": "As we celebrate our 100th anniversary in 2020, we look forward to a special season of performances that honor our past while pointing toward our exciting future. We remain committed to our founding vision of providing accessible, thought-provoking, and entertaining theatrical experiences for our community.",

    
    // Visit Rules
    "rules.title": "Visit Rules",
    "rules.title1": "Rules of visiting the theater",

    "rules.intro": "To ensure an enjoyable experience for all visitors, please familiarize yourself with our theater visit rules.",

    "rules.section1.title": "Before the performance",
    "rules.section1.rule1": "Arrive at least 30 minutes before the performance start time. Latecomers will only be seated at appropriate intervals.",
    "rules.section1.rule2": "Check your tickets for the correct date, time, and seat location.",
    "rules.section1.rule3": "Turn off all electronic devices or switch them to silent mode.",
    "rules.section1.rule4": "Consider checking large bags and outerwear at our complimentary coat check.",
    "rules.section1.rule5": "Food and beverages purchased from our theater café may be consumed in the lobby but are not permitted in the auditorium.",
    "rules.section1.rule6": "Smoking is prohibited in the entire theater building",
    "rules.section2.title": "During the Performance",
    "rules.section2.rule1": "Remain seated until intermission or the end of the performance.",
    "rules.section2.rule2": "Photography and recording of any kind are strictly prohibited.",
    "rules.section2.rule3": "Refrain from talking or creating disturbances during the performance.",
    "rules.section2.rule4": "In case of emergency, follow the instructions of theater staff.",
    "rules.section3.title": "Dress Code",
    "rules.section3.rule": "While there is no formal dress code at TheatreTix, we encourage smart-casual attire for evening performances. For matinees and family shows, casual dress is perfectly acceptable. Some special events may have specific dress requirements, which will be noted on the event page.",
    "rules.section4.title": "Children at Performances",
    "rules.section4.rule1": "Children under 5 years old are not permitted at regular performances unless specifically designated as family or children's shows.",
    "rules.section4.rule2": "All children must have their own ticket and seat.",
    "rules.section4.rule3": "Parents are responsible for ensuring their children do not disturb other patrons.",
    "rules.section4.rule4": "Booster seats are available free of charge at the information desk.",

    "disabled.title": "For Persons with Disabilities",
    "disabled.intro": "TheatreTix is committed to making our theater accessible to all patrons, including those with disabilities.",
    "disabled.section1.title": "Accessibility Features",
    "disabled.section1.rule1": "Wheelchair accessible entrances are located at the main entrance and side entrances.",
    "disabled.section1.rule2": "Wheelchair spaces are available in multiple locations throughout the theater.",
    "disabled.section1.rule3": "Accessible restrooms are located on all levels of the theater.",
    "disabled.section1.rule4": "Service animals are welcome in all areas of the theater.",
    "disabled.section1.rule5": "Assisted listening devices are available free of charge at the information desk.",
    "disabled.section2.title": "Special Performances",
    "disabled.section2.rule": "We regularly schedule performances that include audio description, captioning, and ASL interpretation. Please check our website or contact our box office for details on upcoming accessible performances.",
    "disabled.section3.title": "Booking Assistance",
    "disabled.section3.rule": "If you require any special assistance when booking tickets or attending performances, please contact our accessibility team at least 48 hours in advance at accessibility@theatretix.com or call (123) 456-7890.",
    
    
    "privileged.title": "Visiting the Theater by Privileged Categories of Citizens",
    "privileged.intro": "TheatreTix offers special ticket pricing and access programs for various groups of privileged citizens to ensure that our theater remains accessible to all members of our community.",
    "privileged.section1.title": "Eligible Groups",
    "privileged.section1.rule1": "Senior citizens (aged 65 and above)",
    "privileged.section1.rule2": "Students with valid student ID",
    "privileged.section1.rule3": "Veterans and active military personnel",
    "privileged.section1.rule4": "Persons with disabilities",
    "privileged.section1.rule5": "Low-income individuals participating in our community access program",
    "privileged.section2.title": "Discount Information",
    "privileged.section2.rule1": "Eligible patrons receive a 20% discount on regular ticket prices.",
    "privileged.section2.rule2": "Proof of eligibility must be presented when purchasing tickets or at the box office when collecting tickets.",
    "privileged.section2.rule3": "Limited rush tickets may be available for 50% off one hour before select performances, subject to availability.",
    "privileged.section2.rule4": "Special group rates are available for groups of 10 or more.",
    "privileged.section3.title": "How to Purchase",
    "privileged.section3.rule": "Privileged category tickets can be purchased online (select «Discounted Tickets» during checkout), by phone, or in person at our box office. Please note that you may be required to show proof of eligibility when collecting your tickets.",
    "privileged.section4.rule": "For more information about our privileged category ticket program, please contact our box office at tickets@theatretix.com or call (123) 456-7890.",
    
    
    // Contacts
    "contacts.title": "Contact Information",
    "contacts.location.title": "Theater Location",
    "contacts.location.street": "50 Volodymyrska St.",
    "contacts.location.city": "01030, Kyiv",
    "contacts.location.country": "Ukraine",

    "contacts.hours.title": "Hours of Operation",
    "contacts.hours.boxOffice": "Box Office:",
    "contacts.hours.boxOfficeHours": "Monday - Friday: 10:00 AM - 7:00 PM",
    "contacts.hours.admin": "Administrative Office:",
    "contacts.hours.adminHours": "Monday - Friday: 9:00 AM - 5:00 PM",
    "contacts.hours.performance": "Performance Days:",
    "contacts.hours.performanceOpen": "Box office open until showtime",
    
    "contacts.social.title": "Follow Us",
    
    "contacts.departments.title": "Contact Departments",
    
    "contacts.boxOffice.title": "Box Office",
    "contacts.boxOffice.phoneTitle": "Phone:",
    "contacts.boxOffice.phone": "+380 44 123 4567",
    "contacts.boxOffice.emailTitle": "E-mail:",
    "contacts.boxOffice.email": "tickets@theatretix.com",
    "contacts.boxOffice.description": "For ticket purchases, reservations, and information about upcoming performances.",
    
    "contacts.info.title": "Information Service",
    "contacts.info.phoneTitle": "Phone:",
    "contacts.info.phone": "+380 44 123 4568",
    "contacts.info.emailTitle": "E-mail:",
    "contacts.info.email": "info@theatretix.com",
    "contacts.info.description": "General inquiries, accessibility information, and group bookings.",
    
    "contacts.admin.title": "Administrative Office",
    "contacts.admin.phoneTitle": "Phone:",
    "contacts.admin.phone": "+380 44 123 4569",
    "contacts.admin.emailTitle": "E-mail:",
    "contacts.admin.email": "admin@theatretix.com",
    "contacts.admin.description": "Administrative matters, partnership opportunities, and sponsorships.",
    
    "contacts.accounting.title": "Accounting Department",
    "contacts.accounting.phoneTitle": "Phone:",
    "contacts.accounting.phone": "+380 44 123 4570",
    "contacts.accounting.emailTitle": "E-mail:",
    "contacts.accounting.email": "finance@theatretix.com",
    "contacts.accounting.description": "Invoices, payments, and financial inquiries.",
    
    // Profile
    "profile.title": "Your Profile",
    "profile.tabs.info": "Personal Information",
    "profile.tabs.tickets": "My Tickets",
    "profile.edit": "Edit Profile",
    "profile.username": "Username",
    "profile.firstName": "First Name",
    "profile.firstName.required": "First name is required",
    "profile.lastName": "Last Name",
    "profile.lastName.required": "Last name is required",
    "profile.email": "Email",
    "profile.cancel": "Cancel",
    "profile.save": "Save Changes",
    "profile.tickets.title": "Your Tickets",
    "profile.tickets.subtitle": "All your purchased tickets for upcoming performances",
    "profile.tickets.empty.title": "No tickets yet",
    "profile.tickets.empty.subtitle": "You haven't purchased any tickets yet.",
    "profile.tickets.download": "Download",
    "profile.tickets.return": "Return",
    "profile.deleteProfile" : "Delete Profile",
    "profile.editUsername": "Edit Username",
    "profile.editPassword": "Edit Password",
    "profile.oldPassword": "Old Password",
    "profile.newPassword": "New Password",

    // Login
    "login.title": "Login",
    "login.description": "Log in to access your TheatreTix account",
    "login.username.label": "Username",
    "login.username.placeholder": "Enter your username",
    "login.password.label": "Password",
    "login.password.placeholder": "Enter your password",
    "login.button": "Login",
    "login.adminNotice": "Admin login detected! You can use any password to log in as admin.",
    "login.noAccount": "Don't have an account?",
    "login.register": "Register here",
    
    // Register
    "register.title": "Create Account",
    "register.description": "Join TheatreTix to start booking tickets",
    "register.firstName": "First Name",
    "register.firstName.placeholder": "First Name",
    "register.lastName": "Last Name",
    "register.lastName.placeholder": "Last Name",
    "register.email": "E-mail",
    "register.email.placeholder": "E-mail address",
    "register.username": "Username",
    "register.username.placeholder": "Choose a username",
    "register.password": "Password",
    "register.password.placeholder": "Create a password",
    "register.confirmPassword": "Confirm Password",
    "register.confirmPassword.placeholder": "Confirm your password",
    "register.button": "Create Account",
    "register.hasAccount": "Already have an account?",
    "register.login": "Login here",
    
    // Performance Details
    "performance.about": "About",
    "performance.cast": "Cast & Crew",
    "performance.gallery": "Gallery",
    "performance.reviews": "Reviews",
    "performance.buyTickets": "Buy Tickets",
    "performance.about.title": "About the Performance",
    "performance.info": "Performance Info",
    "performance.info.date": "Date:",
    "performance.info.time": "Time:",
    "performance.info.director": "Director:",
    "performance.info.duration": "Duration:",
    "performance.info.durationText": "Approximately 3 hours (with intermission)",
    
    "performance.cast.title": "Cast & Crew",
    "performance.cast.director": "Director",
    "performance.cast.actors": "Cast",
    "performance.cast.creative": "Creative Team",
    "performance.cast.setDesign": "Set Design",
    "performance.cast.costumeDesign": "Costume Design",
    "performance.cast.lightingDesign": "Lighting Design",
    "performance.cast.soundDesign": "Sound Design",
    "performance.cast.choreography": "Choreography",
    
    "performance.gallery.title": "Performance Gallery",
    
    "performance.reviews.title": "Reviews",
    "performance.reviews.writeReview": "Write a Review",
    "performance.reviews.yourRating": "Your Rating:",
    "performance.reviews.yourComment": "Your Comment:",
    "performance.reviews.commentPlaceholder": "Share your thoughts about the performance...",
    "performance.reviews.submit": "Submit Review",
    "performance.reviews.loginToReview": "Please log in to leave a review",
    "performance.reviews.loginButton": "Login to Review",
    "performance.reviews.empty.title": "No reviews yet",
    "performance.reviews.empty.subtitle": "Be the first to review this performance!",
    "performance.reviews.save": "Save",
    "performance.reviews.cancel": "Cancel",
    
    // Tickets
    "tickets.buy": "Buy Tickets",

    "tickets.selectSeats": "Select Your Seats",
    "tickets.selectSeatsSubtitle": "Choose your preferred seating level and select your seats",

    "tickets.stage": "STAGE",

    "tickets.available": "Available",
    "tickets.selected": "Selected",
    "tickets.NotAvailable": "Not Available",

    "tickets.legend": "Legend:",
    
    "tickets.taken": "Taken",
    "tickets.seatingLevels": "Seating Levels:",
    "tickets.parterre": "Parterre",
    "tickets.mezzanine": "Mezzanine",
    "tickets.tier1": "1st Tier",
    "tickets.tier2": "2nd Tier",
    "tickets.tier3": "3rd Tier",

    "tickets.yourOrder": "Your Order",
    "tickets.yourOrderSubtitle": "Review your selected seats",
    "tickets.noSeats": "No seats selected",
    "tickets.proceedPayment": "Proceed to Payment",
    "tickets.privilegeDocument": "I have a privilege document (-20%)",
    "tickets.privilegeDocumentNumber": "Privilege Document Number",
    "tickets.verify": "Verify",
    "tickets.total": "Total:",

    "tickets.performance": "Performance:",
    "tickets.date": "Date:",
    "tickets.time": "Time:",
    "tickets.selectedSeats": "Selected Seats:",
    "tickets.seat": "Seat",
    "tickets.price": "Price",
    
    "tickets.complete": "Complete Your Purchase",
    "tickets.completeSubtitle": "Enter payment details to complete your order",
    "tickets.orderSum": "Order Summary",
    "tickets.on": "on",
    "tickets.at": "at",
    "tickets.seats": "seats:",
    "tickets.discountApply": "20% privilege discount applied",

    "tickets.paymentInf": "Payment Information",
    "tickets.cardholder": "Cardholder Name",
    "tickets.cardnumber": "Card Number",
    "tickets.expirationDate": "Expiration Date",
    "tickets.securityDate": "Security Code",
    "tickets.nameCard": "Name of card",
    "tickets.monthYear": "MM/YY",

    "tickets.backButton": "Back",
    "tickets.completePurchaseButton": "Complete Purchase",
    
    // News
    "news.title": "Theater News",
    
    // Common
    "language.english": "English",
    "language.ukrainian": "Ukrainian",
    "common.success": "Success",
    "common.error": "Error",
    "common.required": "This field is required"
  },
  ua: {
    // Navigation
    "nav.home": "Головна",
    "nav.schedule": "Афіша",
    "nav.team": "Трупа",
    "nav.aboutTheater": "Про театр",
    "nav.news": "Новини",
    "nav.theaterHistory": "Історія театру",
    "nav.visitRules": "Правила відвідування",
    "nav.contacts": "Контакти",
    "nav.profile": "Профіль",
    "nav.login": "Увійти",
    "nav.register": "Зареєструватися",
    "nav.logout": "Вийти",
    "nav.admin": "Адмін",
    
    // Schedule page
    "schedule.title": "Афіша",
    "schedule.subtitle": "Перегляньте та забронюйте наші майбутні вистави",
    "schedule.allMonths": "Всі місяці",
    "schedule.moreDetails": "Детальніше",
    "schedule.buyTickets": "Купити квитки",
    "schedule.ticketsFrom": "Квитки від",
    "schedule.director": "Режисер",
    "schedule.noPerformances": "Вистав не знайдено",
    "schedule.noPerformancesSubtitle": "На цей період немає запланованих вистав.",
    
    // About pages
    "about.history": "Історія театру",
    "about.rules": "Правила відвідування",
    "about.disabled": "Для осіб з інвалідністю",
    "about.privileged": "Відвідування театру пільговими категоріями громадян",
    "about.contacts": "Контакти",
    "about.redirecting": "Перенаправлення на сторінку історії театру...",
    
    // Search
    "search.title": "Пошук",
    "search.placeholder": "Пошук вистав, акторів, новин...",
    "search.button": "Шукати",
    "search.results": "Знайдено {count} результат",
    "search.results_plural": "Знайдено {count} результатів",
    "search.noResults": "Результатів не знайдено",
    "search.tryAgain": "Спробуйте інші ключові слова або перевірте правопис",
    
    // Admin Panel
    "admin.title": "Адмін",
    "admin.performances": "Управління виставами",
    "admin.performances.subtitle": "Керування театральними виставами - додавання, редагування та видалення вистав.",
    "admin.tickets": "Ціни на квитки",
    "admin.tickets.subtitle": "Встановлення та оновлення цін на квитки на різні секції.",
    "admin.reports": "Звіти про транзакції",
    "admin.reports.subtitle": "Створення та експорт звітів про транзакції.",
    "admin.salaries": "Зарплати співробітників",
    "admin.salaries.subtitle": "Розрахунок зарплат для працівників театру.",
    "admin.news": "Управління новинами",
    "admin.news.subtitle": "Керування новинами - створення, редагування та видалення новин.",
    
    "admin.add": "Додати новий",
    "admin.edit": "Редагувати",
    "admin.delete": "Видалити",
    "admin.save": "Зберегти",
    "admin.cancel": "Скасувати",
    "admin.confirm": "Підтвердити",
    
    "admin.performances.title": "Вистави",
    "admin.performances.new": "Нова вистава",
    "admin.performances.edit": "Редагувати виставу",
    "admin.performances.name": "Назва вистави",
    "admin.performances.date": "Дата",
    "admin.performances.time": "Час",
    "admin.performances.description": "Опис",
    "admin.performances.actions": "Дії",
    "admin.performances.addNewButton": "Додати нову",
    "admin.performances.ActorButton": "Додати актора",
    "admin.performances.addCreativeButton": "Додати творця",
    "admin.performances.nameHuman": "Ім'я",
    "admin.performances.roleHuman": "Роль",
    "admin.performances.photos": "Фотографії",
    "admin.performances.participants": "Учасники",
    "admin.performances.director": "Режисер",
    "admin.performances.actors": "Актори",
    "admin.performances.creativeTeam": "Творча команда",
    "admin.performances.uploadPhoto": "Завантажити фото",
    
    "admin.tickets.title": "Ціни на квитки",
    "admin.tickets.performance": "Вистава",
    "admin.tickets.section": "Секція",
    "admin.tickets.price": "Ціна",
    "admin.tickets.setPrice": "Встановити ціну",
    "admin.tickets.currency": "ГРН",
    "admin.tickets.actions": "Дії",
    
    "admin.reports.title": "Звіти про транзакції",
    "admin.reports.dateRange": "Діапазон дат",
    "admin.reports.from": "Від",
    "admin.reports.to": "До",
    "admin.reports.generate": "Створити звіт",
    "admin.reports.export": "Експортувати в Excel",
    "admin.reports.total": "Загальний дохід",
    "admin.reports.ticketsSold": "Продано квитків",
    "admin.reports.sum": "Підсумок",
    "admin.reports.performance": "Вистава",
    "admin.reports.section": "Секція",
    "admin.reports.date": "Дата",
    "admin.reports.price": "Ціна", 
    "admin.reports.customer": "Покупець",
    
    "admin.salaries.title": "Зарплати співробітників",
    "admin.salaries.calculateTitle": "Розрахувати зарплату",
    "admin.salaries.employee": "Працівник",
    "admin.salaries.hours": "Робочі години",
    "admin.salaries.rate": "Погодинна ставка",
    "admin.salaries.total": "Загальна зарплата",
    "admin.salaries.calculate": "Розрахувати зарплату",
    "admin.salaries.setRate": "Встановити ставку",
    "admin.salaries.selectEmployee": "Виберіть працівника",
    "admin.salaries.setHourlyRate": "Встановити погодинну ставку",
    "admin.salaries.setHourlyRateEmployee": "Встановлення погодинної ставки для",
    "admin.salaries.currentHourlyRate": "Поточна погодинна ставка:",
    "admin.salaries.currentRate": "Поточна ставка",
    "admin.salaries.newRate": "Нова ставка",
    "admin.salaries.name": "Ім'я",
    "admin.salaries.position": "Посада",
    "admin.salaries.actions": "Дії",
    "admin.salaries.cancelButton": "Назад",
    "admin.salaries.saveButton": "Зберегти",
    "admin.salaries.addEmployee": "Додати працівника",
    "admin.salaries.workingDays": "Робочі дні",
    "admin.salaries.dailySalary": "Щоденна зарплата",
    "admin.salaries.monthlySalary": "Щомісячна зарплата",
    "admin.salaries.editSuccess": "Інформація відредагована",
    "admin.salaries.editSuccessDesc": "Інформація про співробітника була успішно відредагована.",
    "admin.salaries.addSuccess": "Працівника додано",
    "admin.salaries.addSuccessDesc": "Новий працівник був успішно доданий.",
    "admin.salaries.deleteSuccess": "Працівника видалено",
    "admin.salaries.deleteSuccessDesc": "Працівник був успішно видалений.",
    "admin.salaries.editEmployee": "Редагувати працівника",


    "admin.news.title": "Управління новинами",
    "admin.news.new": "Нова стаття",
    "admin.news.edit": "Редагувати статтю",
    "admin.news.articleTitle": "Заголовок",
    "admin.news.content": "Зміст",
    "admin.news.date": "Дата публікації",
    "admin.news.photo": "Фото",
    "admin.news.uploadPhoto": "Завантажити фото",
    "admin.news.add": "Додати новину",
    "admin.news.save": "Зберегти новину",

    // Home page
    "home.hero.title": "Відчуйте магію живого театру",
    "home.hero.subtitle": "Забронюйте квитки зараз на найзахопливіші вистави TheatreTix",
    "home.button.schedule": "Переглянути афішу",
    "home.button.signin": "Увійти",
    
    "home.upcoming.title": "Майбутні вистави",
    "home.upcoming.subtitle": "Не пропустіть ці вражаючі шоу",
    "home.upcoming.button": "Усі вистави",
    
    "home.whyus.title": "Чому обирають TheatreTix?",
    "home.whyus.feature1.title": "Відібрані вистави",
    "home.whyus.feature1.text": "Ми ретельно відбираємо найзахопливіші та найрозважальніші шоу для вашого задоволення.",
    "home.whyus.feature2.title": "Просте бронювання",
    "home.whyus.feature2.text": "Наша інтуїтивна платформа спрощує пошук та бронювання ідеальних місць для будь-якого шоу.",
    "home.whyus.feature3.title": "Ексклюзивні знижки",
    "home.whyus.feature3.text": "Спеціальні пропозиції та знижки для членів та постійних відвідувачів театру.",
    "home.whyus.button": "Приєднатися до TheatreTix",
    
    "home.testimonials.title": "Відгуки наших глядачів",
    "home.testimonials.review1.text": "Вистава «Гамлет» була захоплююча. Я сидів на краю сидіння весь час.",
    "home.testimonials.review1.name": "Джеймс Вілсон",
    "home.testimonials.review1.role": "Театральний ентузіаст",
    "home.testimonials.review2.text": "Бронювати квитки було так легко, а місця були точно такими, як описано. Обов'язково скористаюся TheatreTix знову!",
    "home.testimonials.review2.name": "Сара Джонсон",
    "home.testimonials.review2.role": "Постійний відвідувач",
    "home.testimonials.review3.text": "Костюми та декорації для «Ромео і Джульєтти» були абсолютно приголомшливими. Справжня візуальна насолода!",
    "home.testimonials.review3.name": "Майкл Браун",
    "home.testimonials.review3.role": "Арт-директор",
    
    "home.newsletter.title": "Будьте в курсі",
    "home.newsletter.text": "Підпишіться на нашу розсилку і першими дізнавайтеся про майбутні шоу, спеціальні пропозиції та ексклюзивні події.",
    "home.newsletter.placeholder": "Введіть вашу електронну адресу",
    "home.newsletter.button": "Підписатися",

    // Footer
    "footer.description": "TheatreTix – ваша головна зупинка для театральних вистав у місті. Ми забезпечуємо незабутній культурний досвід з різноманітними класичними та сучасними постановками.",
    "footer.quickLinks": "Швидкі посилання",
    "footer.contact": "Контакти",
    "footer.hours": "Години роботи",
    "footer.address": "вул. Володимирська 50",
    "footer.phone": "+380 44 123 4567",
    "footer.email": "info@theatretix.com",
    "footer.weekdays": "Пн-Пт: 9:00 - 20:00",
    "footer.weekends": "Сб-Нд: 10:00 - 18:00",
    "footer.allRights": "Всі права захищені",
    "footer.privacy": "Політика конфіденційності",
    "footer.termsService": "Умови надання послуг",
    "footer.refund": "Політика повернення коштів",

    // Team
    "team.title": "Наша команда",
    "team.tabs.management": "Керівництво",
    "team.tabs.actors": "Актори",
    "team.tabs.creative": "Творча група",
    "team.tabs.directors": "Постановщики",
    
    "team.management.title": "Керівництво театру",
    "team.actors.title": "Наші актори",
    "team.creative.title": "Творча команда",
    "team.directors.title": "Наші постановщики",

    // About Theater History
    "history.title": "Історія театру",
    "history.intro": "Наш театр має багату історію, що налічує понад століття, розвиваючись від скромних початків до однієї з провідних культурних установ країни.",
    "history.section1.title": "Ранні роки (1920-1945)",
    "history.section1.text": "Заснований у 1920 році відомим режисером і драматургом Антоном Михайловим, наш театр почав свій шлях як маленька експериментальна сцена в самому серці міста. Протягом перших десятиліть театр утвердився як центр інноваційних вистав та запустив кар'єри багатьох прославлених акторів.",
    "history.section1.caption": "Оригінальна будівля театру, приблизно 1925 рік",
    "history.section2.title": "Золота доба (1945-1970)",
    "history.section2.text": "Післявоєнний період ознаменував золоту добу театру, з легендарними постановками класичних і сучасних творів, що здобули міжнародне визнання. Під керівництвом Марії Степанової театр розширив свій репертуар і привабив найкращі таланти країни.",
    "history.section2.caption": "Відома постановка «Вишневого саду», 1956 рік",
    "history.section3.title": "Сучасна епоха (1970-сьогодні)",
    "history.section3.text": "Останні десятиліття наш театр охопив передові постановки, шануючи при цьому театральні традиції. Капітальний ремонт у 2010 році модернізував наші приміщення, зберігаючи історичну чарівність нашої головної будівлі. Сьогодні ми продовжуємо розсувати межі та взаємодіяти з аудиторією через потужне оповідання та художню досконалість.",
    "history.section3.caption": "Відреставрована головна сцена, 2012 рік",
    "history.section4.title": "Нагороди та визнання",
    "history.section4.text": "Протягом своєї історії TheatreTix отримав численні нагороди та відзнаки, зокрема:",
    "history.section4.point1": "Національна театральна премія (1978, 1992, 2008)",
    "history.section4.point2": "Регіональний театр року (2012, 2019)",
    "history.section4.point3": "Нагорода за вплив на місцеве мистецтво (щорічно з 2005)",
    "history.section4.point4": "Нагорода за збереження історичної спадщини за реставрацію нашої будівлі (2015)",
    "history.section5.title": "Святкування нашого сторіччя",
    "history.section5.text": "Відзначаючи наше 100-річчя у 2020 році, ми з нетерпінням чекаємо на особливий сезон вистав, які вшановують наше минуле і водночас вказують на наше захоплююче майбутнє. Ми залишаємось відданими нашому основоположному баченню - надавати нашій громаді доступні, спонукаючі до роздумів та розважальні театральні враження.",

    
    // Visit Rules
    "rules.title": "Правила відвідування",

    "rules.title1": "Правила відвідування театру",
    "rules.intro": "Щоб забезпечити приємний досвід для всіх відвідувачів, будь ласка, ознайомтеся з правилами відвідування нашого театру.",

    "rules.section1.title": "Перед виставою",
    "rules.section1.rule1": "Приходьте щонайменше за 30 хвилин до початку вистави. Ті, хто запізниться, будуть розсаджені лише через певні проміжки часу.",
    "rules.section1.rule2": "Перевірте свої квитки на правильність дати, часу та місця у залі.",
    "rules.section1.rule3": "Вимкніть усі електронні пристрої або переведіть їх у беззвучний режим.",
    "rules.section1.rule4": "Подумайте про перевірку великих сумок і верхнього одягу на нашій безкоштовній камері схову.",
    "rules.section1.rule5": "Їжу та напої, придбані в кав'ярні театру, можна вживати у фойє, але заборонено проносити до глядацької зали.",
    "rules.section1.rule6": "Паління заборонено у всій будівлі театру",
    "rules.section2.title": "Під час вистави",
    "rules.section2.rule1": "Залишайтеся на своїх місцях до антракту або закінчення вистави.",
    "rules.section2.rule2": "Фотографування та запис у будь-якому вигляді суворо заборонені.",
    "rules.section2.rule3": "Утримайтеся від розмов і не створюйте перешкод під час вистави.",
    "rules.section2.rule4": "У разі надзвичайної ситуації дотримуйтесь інструкцій працівників театру.",
    "rules.section3.title": "Дрес-код",
    "rules.section3.rule": "Хоча в TheatreTix немає формального дрес-коду, ми заохочуємо відвідувати вечірні вистави в стилі smart-casual. Для ранкових та сімейних вистав цілком прийнятним є повсякденний одяг. Деякі спеціальні події можуть мати особливі вимоги до одягу, про що буде вказано на сторінці події.",
    "rules.section4.title": "Діти на виставах",
    "rules.section4.rule1": "Діти до 5 років не допускаються на звичайні вистави, якщо тільки вони спеціально не позначені як сімейні або дитячі.",
    "rules.section4.rule2": "Усі діти повинні мати власний квиток і місце в залі.",
    "rules.section4.rule3": "Батьки несуть відповідальність за те, щоб їхні діти не заважали іншим відвідувачам.",
    "rules.section4.rule4": "На інформаційній стійці можна безкоштовно отримати додаткові місця для дітей.",

    "disabled.title": "Для осіб з інвалідністю",
    "disabled.intro": "TheatreTix прагне зробити наш театр доступним для всіх відвідувачів, включаючи людей з інвалідністю.",
    "disabled.section1.title": "Особливості доступності",
    "disabled.section1.rule1": "В'їзди, пристосовані для людей на візках, розташовані біля головного та бічних входів.",
    "disabled.section1.rule2": "Місця для інвалідних візків доступні в різних місцях по всьому театру.",
    "disabled.section1.rule3": "Доступні туалети розташовані на всіх рівнях театру.",
    "disabled.section1.rule4": "У всіх приміщеннях театру зустрічають службові тварини.",
    "disabled.section1.rule5": "Слухові апарати з підтримкою слуху можна безкоштовно отримати на інформаційній стійці.",
    "disabled.section2.title": "Спеціальні вистави",
    "disabled.section2.rule": "Ми регулярно проводимо вистави з аудіодискрипцією, субтитрами та перекладом мовою жестів. Будь ласка, відвідайте наш веб-сайт або зверніться до нашої каси, щоб дізнатися про найближчі доступні вистави.",
    "disabled.section3.title": "Допомога з бронюванням",
    "disabled.section3.rule": "Якщо вам потрібна спеціальна допомога з бронюванням квитків або відвідуванням вистави, будь ласка, зв'яжіться з нашою командою з питань доступності щонайменше за 48 годин до вистави за адресою accessibility@theatretix.com або зателефонуйте за номером (123) 456-7890.",

    "privileged.title": "Відвідування театру пільговими категоріями громадян",
    "privileged.intro": "TheatreTix пропонує спеціальні ціни на квитки та програми доступу для різних груп привілейованих громадян, щоб гарантувати, що наш театр залишається доступним для всіх членів нашої громади.",
    "privileged.section1.title": "Відповідні групи",
    "privileged.section1.rule1": "Люди похилого віку (віком від 65 років)",
    "privileged.section1.rule2": "Студенти з дійсним студентським квитком",
    "privileged.section1.rule3": "Ветерани та діючі військовослужбовці",
    "privileged.section1.rule4": "Особи з обмеженими можливостями",
    "privileged.section1.rule5": "Малозабезпечені особи, які беруть участь у нашій програмі доступу до громади",
    "privileged.section2.title": "Інформація про знижки",
    "privileged.section2.rule1": "Меценати, які мають на це право, отримують 20% знижку від звичайної ціни на квитки.",
    "privileged.section2.rule2": "Підтвердження права на знижку необхідно пред'явити при купівлі квитків або в касі при отриманні квитків.",
    "privileged.section2.rule3": "Обмежена кількість квитків може бути продана зі знижкою 50% за годину до початку окремих вистав, за умови наявності вільних місць.",
    "privileged.section2.rule4": "Спеціальні групові ціни доступні для груп від 10 осіб.",
    "privileged.section3.title": "Як придбати",
    "privileged.section3.rule": "Квитки для пільгових категорій можна придбати онлайн (оберіть «Пільгові квитки» під час оформлення замовлення), по телефону або особисто в нашій касі. Зверніть увагу, що при отриманні квитків у вас можуть попросити пред'явити посвідчення, що підтверджує вашу пільгову категорію.",
    "privileged.section4.rule": "Для отримання додаткової інформації про нашу програму пільгових квитків, будь ласка, звертайтеся до нашої каси за адресою tickets@theatretix.com або за телефоном (123) 456-7890.",
    
    // Contacts
    "contacts.title": "Контактна інформація",
    "contacts.location.title": "Розташування театру",
    "contacts.location.street": "вул. Володимирська 50",
    "contacts.location.city": "01030, м. Київ",
    "contacts.location.country": "Україна",

    "contacts.hours.title": "Години роботи",
    "contacts.hours.boxOffice": "Каса:",
    "contacts.hours.boxOfficeHours": "Понеділок - п'ятниця: 10:00 - 19:00",
    "contacts.hours.admin": "Адміністрація:",
    "contacts.hours.adminHours": "Понеділок - п'ятниця: 9:00 - 17:00",
    "contacts.hours.performance": "Дні виступів:",
    "contacts.hours.performanceOpen": "Каса працює до початку сеансу",

    "contacts.departments.title": "Контактні відділи",
    
    "contacts.boxOffice.title": "Каса",
    "contacts.boxOffice.phoneTitle": "Телефон:",
    "contacts.boxOffice.phone": "+380 44 123 4567",
    "contacts.boxOffice.emailTitle": "E-mail:",
    "contacts.boxOffice.email": "tickets@theatretix.com",
    "contacts.boxOffice.description": "Для купівлі квитків, бронювання та інформації про майбутні вистави.",
    
    "contacts.info.title": "Інформаційна служба",
    "contacts.info.phoneTitle": "Телефон:",
    "contacts.info.phone": "+380 44 123 4568",
    "contacts.info.emailTitle": "E-mail:",
    "contacts.info.email": "info@theatretix.com",
    "contacts.info.description": "Загальні питання, інформація про доступність та групове бронювання.",
    
    "contacts.admin.title": "Адміністрація",
    "contacts.admin.phoneTitle": "Телефон:",
    "contacts.admin.phone": "+380 44 123 4569",
    "contacts.admin.emailTitle": "E-mail:",
    "contacts.admin.email": "admin@theatretix.com",
    "contacts.admin.description": "Адміністративні питання, можливості партнерства та спонсорства.",
    
    "contacts.accounting.title": "Бухгалтерія",
    "contacts.accounting.phoneTitle": "Телефон:",
    "contacts.accounting.phone": "+380 44 123 4570",
    "contacts.accounting.emailTitle": "E-mail:",
    "contacts.accounting.email": "finance@theatretix.com",
    "contacts.accounting.description": "Рахунки, платежі та фінансові запити.",
    
    "contacts.social.title": "Слідкуйте за нами",
    
    // Profile
    "profile.title": "Ваш профіль",
    "profile.tabs.info": "Особиста інформація",
    "profile.tabs.tickets": "Мої квитки",
    "profile.edit": "Редагувати профіль",
    "profile.username": "Ім'я користувача",
    "profile.firstName": "Ім'я",
    "profile.firstName.required": "Ім'я обов'язкове",
    "profile.lastName": "Прізвище",
    "profile.lastName.required": "Прізвище обов'язкове",
    "profile.email": "Електронна пошта",
    "profile.cancel": "Скасувати",
    "profile.save": "Зберегти зміни",
    "profile.deleteProfile" : "Видалити профіль",
    "profile.editUsername": "Редагувати ім'я користувача",
    "profile.editPassword": "Редагувати пароль",
    "profile.oldPassword": "Старий пароль",
    "profile.newPassword": "Новий пароль",

    "profile.tickets.title": "Ваші квитки",
    "profile.tickets.subtitle": "Усі ваші придбані квитки на майбутні вистави",
    "profile.tickets.empty.title": "Ще немає квитків",
    "profile.tickets.empty.subtitle": "Ви ще не придбали жодного квитка.",
    "profile.tickets.download": "Завантажити",
    "profile.tickets.return": "Повернути",
    
    // Login
    "login.title": "Увійти",
    "login.description": "Увійдіть, щоб отримати доступ до вашого облікового запису TheatreTix",
    "login.username.label": "Ім'я користувача",
    "login.username.placeholder": "Введіть ваше ім'я користувача",
    "login.password.label": "Пароль",
    "login.password.placeholder": "Введіть ваш пароль",
    "login.button": "Увійти",
    "login.adminNotice": "Виявлено вхід адміністратора! Ви можете використовувати будь-який пароль для входу як адміністратор.",
    "login.noAccount": "Немає облікового запису?",
    "login.register": "Зареєструйтеся тут",
    
    // Register
    "register.title": "Створити обліковий запис",
    "register.description": "Приєднуйтесь до TheatreTix, щоб почати бронювати квитки",
    "register.firstName": "Ім'я",
    "register.firstName.placeholder": "Ім'я",
    "register.lastName": "Прізвище",
    "register.lastName.placeholder": "Прізвище",
    "register.email": "Електронна пошта",
    "register.email.placeholder": "Адреса електронної пошти",
    "register.username": "Ім'я користувача",
    "register.username.placeholder": "Виберіть ім'я користувача",
    "register.password": "Пароль",
    "register.password.placeholder": "Створіть пароль",
    "register.confirmPassword": "Підтвердження паролю",
    "register.confirmPassword.placeholder": "Підтвердіть ваш пароль",
    "register.button": "Створити обліковий запис",
    "register.hasAccount": "Вже маєте обліковий запис?",
    "register.login": "Увійдіть тут",
    
    // Performance Details
    "performance.about": "Про виставу",
    "performance.cast": "Актори та команда",
    "performance.gallery": "Галерея",
    "performance.reviews": "Відгуки",
    "performance.buyTickets": "Купити квитки",
    "performance.about.title": "Про виставу",
    "performance.info": "Інформація про виставу",
    "performance.info.date": "Дата:",
    "performance.info.time": "Час:",
    "performance.info.director": "Режисер:",
    "performance.info.duration": "Тривалість:",
    "performance.info.durationText": "Приблизно 3 години (з антрактом)",
    
    "performance.cast.title": "Актори та команда",
    "performance.cast.director": "Режисер",
    "performance.cast.actors": "Актори",
    "performance.cast.creative": "Творча команда",
    "performance.cast.setDesign": "Декорації",
    "performance.cast.costumeDesign": "Костюми",
    "performance.cast.lightingDesign": "Освітлення",
    "performance.cast.soundDesign": "Звук",
    "performance.cast.choreography": "Хореографія",
    
    "performance.gallery.title": "Галерея вистави",
    
    "performance.reviews.title": "Відгуки",
    "performance.reviews.writeReview": "Написати відгук",
    "performance.reviews.yourRating": "Ваша оцінка:",
    "performance.reviews.yourComment": "Ваш коментар:",
    "performance.reviews.commentPlaceholder": "Поділіться своїми думками про виставу...",
    "performance.reviews.submit": "Надіслати відгук",
    "performance.reviews.loginToReview": "Будь ласка, увійдіть, щоб залишити відгук",
    "performance.reviews.loginButton": "Увійти для відгуку",
    "performance.reviews.empty.title": "Ще немає відгуків",
    "performance.reviews.empty.subtitle": "Будьте першим, хто залишить відгук про цю виставу!",
    "performance.reviews.save": "Зберегти",
    "performance.reviews.cancel": "Скасувати",

    // Tickets
    "tickets.buy": "Купити білети",

    "tickets.selectSeats": "Виберіть свої місця",
    "tickets.selectSeatsSubtitle": "Виберіть бажаний рівень та оберіть місця",

    "tickets.stage": "СЦЕНА",

    "tickets.legend": "Легенда:",
    "tickets.available": "Доступно",
    "tickets.selected": "Вибрано",
    "tickets.NotAvailable": "Недоступно",

    "tickets.taken": "Зайнято",
    "tickets.seatingLevels": "Рівні сидінь:",

    "tickets.parterre": "Партер",
    "tickets.mezzanine": "Бельетаж",
    "tickets.tier1": "1-й ярус",
    "tickets.tier2": "2-й ярус",
    "tickets.tier3": "3-й ярус",

    "tickets.yourOrder": "Ваше замовлення",
    "tickets.yourOrderSubtitle": "Перегляньте обрані вами місця",
    "tickets.proceedPayment": "Перейти до оплати",
    "tickets.seat": "Місце",
    "tickets.privilegeDocument": "У мене є пільговий документ (-20%)",
    "tickets.privilegeDocumentNumber": "Номер пільгового документу",
    "tickets.verify": "Підтвердити",
    "tickets.total": "Всього:",

    "tickets.performance": "Вистава:",
    "tickets.date": "Дата:",
    "tickets.time": "Час:",
    "tickets.selectedSeats": "Вибрані місця:",
    "tickets.noSeats": "Місця не вибрані",
    "tickets.price": "Ціна",
    
    "tickets.complete": "Завершіть вашу покупку",
    "tickets.completeSubtitle": "Введіть платіжні реквізити для завершення замовлення",
    "tickets.orderSum": "Підсумок замовлення",
    "tickets.on": "на",
    "tickets.at": "o",
    "tickets.seats": "місця:",
    "tickets.discountApply": "Застосовується пільгова знижка 20%",

    "tickets.paymentInf": "Платіжна інформація",
    "tickets.cardholder": "Ім'я власника картки",
    "tickets.cardnumber": "Номер картки",
    "tickets.expirationDate": "Термін дії",
    "tickets.securityDate": "Код безпеки",
    "tickets.nameCard": "Ім'я карти",
    "tickets.monthYear": "ММ/РР",

    "tickets.backButton": "Назад",
    "tickets.completePurchaseButton": "Завершити покупку",
    
    // News
    "news.title": "Новини театру",
    
    // Common
    "language.english": "Англійська",
    "language.ukrainian": "Українська",
    "common.success": "Успішно",
    "common.error": "Помилка",
    "common.required": "Це поле є обов'язковим"
  }
};

// Provider component
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  // Translation function
  const t = (key: string): string => {
    const translation = translations[language][key];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using the language context
export const useLanguage = () => useContext(LanguageContext);
